export const environment = {
    production: true,
    // base_url: "http://localhost:5000/",
   // base_url: "http://27.34.40.174:9090/",
    // base_url:"http://173.225.107.122:8765/",
  // base_url: "https://kageshwori.soft-acc.com/",
  // base_url: "https://localhost:44366/",
  base_url: "https://backend.serverftp.tech/",
// test
  loginDetails: [
    {
      clientcode: 'kmc-dc',
      mainlogo: '../assets/images/nepal_logo.png',
      mainTitle: 'काठमाडौं महानगरपालिका कार्यालय',
      mainSubtitle: 'Data Collection & Manipulation Portal',
      logo: '../assets/images/kmc_logo.jpg',
      mainHeading: 'काठमाडौं महानगरपालिका कार्यालय',
      logo2: '../assets/image/logo/kmc-logo.png',
      logo3: '../assets/images/Flag_of_Nepal.gif',
      logo4: '../assets/image/logo/newari.png',
      Heading: 'एकीकृत स्थानीय तह वस्तुगत विवरण ',
      Heading2: ' (ILG-Profile)',
      Heading3: ' पारिवारिक विवरण संकलन फाराम',
      slogan: '*"स्वच्छ, सफा हराभरा बनाओ काठमाडौं महानगरपालिका',
      dashTitle: 'KMC Management',
      pageTitle: 'काठमाडौं महानगरपालिका कार्यालय',
      landingPage: 'kmc-dc',
    },
    {
      clientcode: 'pbg',
      mainlogo: '../assets/images/nepal_logo.png',
      mainTitle: 'बडीमालिका नगरपालिका कार्यालय',
      mainSubtitle: 'Data Collection & Manipulation Portal',
      mainHeading: 'बडीमालिका  महानगरपालिका कार्यालय',
      logo: '../assets/images/logo/badimalikamainsmall.png',
      // logo2: '../assets/images/logo/badimalikasmall.png',
      logo3: '../assets/images/Flag_of_Nepal.gif',
      // 'logo4': '../assets/img/logo/badimalikasmall.png',
      Heading: '  एकीकृत स्थानीय तह वस्तुगत विवरण  ',
      Heading2: '   पारिवारिक विवरण संकलन फाराम',
      slogan: ' *"स्वच्छ, सफा हराभरा बनाओ बडीमालिका नगरपालिका ',
      dashTitle: 'Data Collection',
      pageTitle: 'बडीमालिका डिजिटल प्रोफाइल',
      landingPage: 'pbg',
    },
    {
      clientcode: 'kage',
      mainlogo: '../assets/images/nepal_logo.png',
      mainTitle: 'कागेश्वरी मनोहरा नगरपालिका कार्यालय',
      mainSubtitle: 'Data Collection & Manipulation Portal',
      logo: '../assets/images/kage_logo.jpg',
      mainHeading: 'Data Collection & Reporting',
      // logo2: '../assets/img/logo/kmc-logo.png',
      logo3: '../assets/images/Flag_of_Nepal.gif',
      // 'logo4': '../assets/img/logo/newari.png',
      Heading: 'Data Collection & Manipulation Portal',
      Heading2: '',
      Heading3: '',
      slogan: 'स्वच्छ,सफा हराभरा, बनाऔँ कागेश्वरी मनोहरा',
      dashTitle: 'कागेश्वरी मनोहरा नगरपालिका कार्यालय',
      pageTitle: 'कागेश्वरी मनोहरा नगरपालिका कार्यालय',
      landingPage: 'kage',
    },
  ],
  client_code: 'kmc-dc',
};
